apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 3 
  template: 
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: ryoungkin/urlshortener:0.6.0
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  ports:
  - name: http
    targetPort: 9090
    port: 80
  selector:
    app: url-shortener
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: url-shortener-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
        - path: /urlshortener
          backend:
            serviceName: url-shortener-service
            servicePort: http